### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by timomitchel** [jmevans0211/mod_0_skills_class#1]
# Checklist/Rubric

### Part I: Creating Directories and Files; Initializing Git and Pushing to GitHub

- [] I named my directories correctly. 
- [x] I named my files correctly.
- [ ] I structured my files and directories correctly. 
- [x] I made one initial commit.
- [x] I pushed my initial commit to GitHub.

### Part II: Top Down Design

- [x] I broke down larger processes into smaller layers.
- [x] I added and committed my changes with a properly formatted commit message starting with a present-tense verb and a capital letter.
- [x] I pushed my changes to Github. 

### Part III: Classes, Objects, Attributes, and Methods

Class #1 Checklist
- [1/2] I structured and named my directories and files correctly.
- [x] The four attributes I chose for **Class #1** represent properties or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 1**.
- [3/4] The four methods I chose for **Class #1** represent behaviors or actions.
- [x] I described what the methods do in **Class 1**, including which attributes they use or modify.
- [x] I added and committed the `class_1.txt` file **separately** with a properly formatted commit message. 

Class #1 Example Object Checklist
- [x] The object I chose for **Class 1** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_1_example_object.txt` file **separately** with a properly formatted commit message. 

Class #2 Checklist
- [x] The four attributes I chose for **Class #2** represent states or characteristics.
- [x] I identified the data type (string, integer, boolean, array, hash/object, datetime) for attributes in **Class 2**.
- [2/4] The four methods I chose for **Class #2** represent behaviors or actions.
- [x] I described what the methods do in **Class 2**, including which attributes they use or modify.
- [x] I added and committed the `class_2.txt` file **separately** with a properly formatted commit message. 

Class #2 Example Object Checklist
- [x] The object I chose for **Class 2** is an instance of this class. 
- [x] I listed the values for each attribute of this object. 
- [x] I listed the results of each method for this object. 
- [x] I added and committed the `class_2_example_object.txt` file **separately** with a properly formatted commit message. 

Hey Jeannie! Good job on your assessment. You are really close to where we want you to be. We are going to ask you to add to your assessment. We wanted a `classes` directory within your `mod_0_skills` directory, but instead we got two separate directories. One with class files and one with the `top_down_design.md` file.  Go ahead and set up a new directory (outside and independent of either of these two directories that you created for the assessment - so a brand new repo/directory that you will end up pushing to Github) called `assessment_take_two` and initialize it as a git repository and add an initial commit. Then, make a `classes` directory within that directory. Then, within the `classes` directory add a file called `class_3.txt`. For this file we want you to model a class around something you would find in a furniture store. Add four relevant attributes and methods to whichever class that you choose to model in the furniture store, with the same requirements as before on the assessment (The class is named properly, choose one data-type for each attribute, explain what your method does and which attribute it modifies and name your methods as actions/verbs). Make sure that your methods are ALL actions/verbs. We wouldn't ever want to name an attribute and a method the same thing, because our program would have a hard time understanding which one to choose when we referred to it. So instead of `InternetAccess` as a method we could name it something like `giveInternetAccess` or `revokeInternetAccess`. Then create a file named `class_3_example_object.txt` and create an object that is an example of your class. Give your attributes values and your methods return values like you had previously done. Then, commit these changes, and push them to Github. You can commit them together or separately - your choice.  This will require you to set up a new remote repository on Github that you can push to like you've done before. Make sure you only create and turn in one repository. Let us know if you have any questions, and send us a link to your new repository when you are finished. Thanks Jeannie!

### Assessment Results
- [ ] Technical Ready
- [x] Pending
- [ ] Not Technical Ready
